-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 23:03:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop_course_371
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shop_course_371` ;

-- -----------------------------------------------------
-- Schema shop_course_371
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop_course_371` DEFAULT CHARACTER SET utf8 ;
USE `shop_course_371` ;

-- -----------------------------------------------------
-- Table `shop_course_371`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_371`.`category` ;

CREATE TABLE IF NOT EXISTS `shop_course_371`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(128) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_371`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_371`.`category` ;

CREATE TABLE IF NOT EXISTS `shop_course_371`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(128) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_371`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_371`.`product` ;

CREATE TABLE IF NOT EXISTS `shop_course_371`.`product` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `image` VARCHAR(45) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category1_idx` (`category_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_371`.`attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_371`.`attribute` ;

CREATE TABLE IF NOT EXISTS `shop_course_371`.`attribute` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `unit` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_371`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_371`.`users` ;

CREATE TABLE IF NOT EXISTS `shop_course_371`.`users` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_371`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_371`.`clients` ;

CREATE TABLE IF NOT EXISTS `shop_course_371`.`clients` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NULL,
  `phone` VARCHAR(17) NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_371`.`adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_371`.`adress` ;

CREATE TABLE IF NOT EXISTS `shop_course_371`.`adress` (
  `id` INT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `town` VARCHAR(45) NOT NULL,
  `house` VARCHAR(45) NOT NULL,
  `clients_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_adress_clients1_idx` (`clients_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_371`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_371`.`order` ;

CREATE TABLE IF NOT EXISTS `shop_course_371`.`order` (
  `id` INT NOT NULL,
  `date` DATETIME NULL,
  `payment` VARCHAR(45) NULL,
  `delivery` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `clients_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_clients1_idx` (`clients_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_371`.`product_has_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_371`.`product_has_order` ;

CREATE TABLE IF NOT EXISTS `shop_course_371`.`product_has_order` (
  `product_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`product_id`, `order_id`),
  INDEX `fk_product_has_order_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_product_has_order_product1_idx` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_371`.`attribute_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_371`.`attribute_has_product` ;

CREATE TABLE IF NOT EXISTS `shop_course_371`.`attribute_has_product` (
  `attribute_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`attribute_id`, `product_id`),
  INDEX `fk_attribute_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_attribute_has_product_attribute1_idx` (`attribute_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_371`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_371`.`roles` ;

CREATE TABLE IF NOT EXISTS `shop_course_371`.`roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_371`.`roles_has_clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_371`.`roles_has_clients` ;

CREATE TABLE IF NOT EXISTS `shop_course_371`.`roles_has_clients` (
  `roles_id` INT NOT NULL,
  `clients_id` INT NOT NULL,
  PRIMARY KEY (`roles_id`, `clients_id`),
  INDEX `fk_roles_has_clients_clients1_idx` (`clients_id` ASC) VISIBLE,
  INDEX `fk_roles_has_clients_roles1_idx` (`roles_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
